sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  - ./node_modules/.bin/ng test --single-run --code-coverage --no-progress
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run ghpages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $PUSH_TOKEN
  on:
    branch: master
